### ISSUE TITLE
[feature Request] Biome Locking beyond Magma Fields

### ISSUE THREAD

**Issue by LordGrimmauld** [DoomKitty87/route-gen-app#2]
A biome lock that is more flexible than "magma fields only" would be amazing.

Consider the following use case:
I am ironman in need of lapis for terminator. But i also need more powder, blue goblin eggs and hardstone (which is best mined using snail pet). So, ideally i'd have a route through goblin holdout and only goblin holdout so that i can get all those things on one route. Currently, generating a lapis route at high y level in the corner of goblin holdout has the route "escape" to jungle, where i can not get blue eggs.

If there was a selection to restrict the entire route to just one of the five biome (instead of just being restrictable to magma fields) a route like that would be possible and also very helpful.

Sidenote: because i plan to use that route as essentially routed powder, having a way to weigh y movement more harshly than lateral movement  would allow the route to be more efficient, but i understand that is entirely different functionality and not as important as just a biome lock.

Keep up the good work though, this project is quite nice for custom routes with niche use cases as mine. Makes mining so much less painful!

**Comment by DoomKitty87** [comment]
Added biome lock for the four quadrants, let me know if it works how you wanted it to. I tried a couple of quick fixes for the y movement problem, but I think that it would require a rework of the ore generation. It's something I might do in the future, and it would also improve the vein density for ores. Thanks for the suggestions

**Comment by LordGrimmauld** [comment]
Looking good! I will thouroughly test it tomorrow when i have a bit more time though. It is however an interesting choice having the biome lock be independent of magma fields, seeing as magma fields too is a biome. I can not think of a scenario where you'd need to lock to a quadrant and then mine magma fields exclusive. In my mind it'd make more sense having magma fields be just another selectable option in biome lock.

**Comment by DoomKitty87** [comment]
That's a good point- I was thinking of it from the perspective of gem mining, but that makes sense. I will change it to that.
